#!/bin/bash



LIST=$(nm $1 | awk '{print $3}' | grep "_$" | grep -v __ | grep -v  "^_" | grep -v timer_ | grep -v print_results_ | sort | uniq | sed s/.$//)

echo $LIST

for sym in $LIST; do
	echo $sym;
	echo find . -name "*.[hf]" |xargs sed -i s/\\b$sym\\b/${sym}_b/g;
done

# gcc -O2 -fopenmp -o test2 BT-*/bt.o  BT-*/initialize.o BT-*/exact_solution.o BT-*/exact_rhs.o BT-*/set_constants.o BT-*/adi.o  BT-*/rhs.o BT-*/x_solve.o BT-*/y_solve.o BT-*/solve_subs.o BT-*/z_solve.o BT-[ab]/add.o BT-[ab]/error.o BT-[ab]/verify.o common/print_results.o common/timers.o common/wtime.o starter_pt.c -lgfortran -Wall -pthread
